repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # Use the latest revision of Black
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]
      - id: check-yaml
      - id: debug-statements
        language_version: python3
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python run_pytest.py
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
